version: "3.9"

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    volumes:
      - ./test_files/certs:/vault/userconfig/tls-server
      - ./test_files/vault:/mnt
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: SiQOECxwSDCeQt1r0n5kqQCr
      VAULT_LOG_LEVEL: debug
      VAULT_CACERT: /vault/userconfig/tls-server/ca.crt
      VAULT_ADDR: https://127.0.0.1:8400
      VAULT_TOKEN: SiQOECxwSDCeQt1r0n5kqQCr
    command:
      - server
      - -dev
      - -config=/mnt/tls-config.hcl
    networks:
      - vault-kms-provider
    expose:
      - 8400:8400

  vault-kms-provider:
    environment:
      VAULT_ADDRESS: https://vault:8400
      VAULT_TOKEN: SiQOECxwSDCeQt1r0n5kqQCr
      VAULT_CACERT: /etc/ssl/certs/ca.crt
      SOCKET_PATH: /sockets/vault-kms-provider.sock
      LOG_LEVEL: info
    build:
      args:
        UID: 0
        GID: 0
      dockerfile: ./Dockerfile
    container_name: vault-kms-provider
    networks:
      - vault-kms-provider
    volumes:
      - ./sockets:/sockets
      - ./test_files/certs:/etc/ssl/certs

networks:
  vault-kms-provider:
    name: vault-kms-provider-net