apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (or .Values.volumeMounts .Values.vault.ca.secret.enabled) .Values.serviceAccount.create }}
      volumes:
        {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        {{- if .Values.vault.ca.secret.mountPath }}
        - name: {{ .Values.vault.ca.secret.name }}
          secret:
            secretName: {{ .Values.vault.ca.secret.name }}
        {{- end }}
        {{- if and (and .Values.serviceAccount.create .Values.serviceAccount.token.name) .Values.serviceAccount.token.path }}
        - name: {{ .Values.serviceAccount.token.name }}
          projected:
            sources:
              - serviceAccountToken:
                  path: {{ .Values.serviceAccount.token.name }}
                  expirationSeconds: 3600
                  audience: vault
        {{- end }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- if .Values.vault.token.set }}
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vault.token.name }}
                  key: {{ .Values.vault.token.key }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          {{- if or (or (and .Values.serviceAccount.token.name .Values.serviceAccount.token.path) .Values.volumeMounts) .Values.vault.ca.secret.enabled }}
          volumeMounts:
            {{- if .Values.volumeMounts }}
            {{- .Values.volumeMounts | toYaml | nindent 12 }}
            {{- end }}
            {{- if and .Values.serviceAccount.token.name .Values.serviceAccount.token.path }}
            - name: {{ .Values.serviceAccount.token.name }}
              mountPath: {{ .Values.serviceAccount.token.path }}
            {{- end }}
            {{- if .Values.vault.ca.secret.mountPath }}
            - name: {{ .Values.vault.ca.secret.name }}
              mountPath: {{ .Values.vault.ca.secret.mountPath}}
              {{- if .Values.vault.ca.secret.subPath }}
              subPath: {{ .Values.vault.ca.secret.subPath }}
              {{- end }}
              readOnly: true
            {{- end }}
          {{- end }}