apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.socketVolume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.socketVolume.claim }}
        {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        {{- if and (and .Values.serviceAccount.create .Values.serviceAccount.token.name) .Values.serviceAccount.token.path }}
        - name: {{ .Values.serviceAccount.token.name }}
          projected:
            sources:
              - serviceAccountToken:
                  path: {{ .Values.serviceAccount.token.name }}
                  expirationSeconds: 3600
                  audience: vault
        {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if .Values.envFrom }}
              {{- toYaml .Values.envFrom | nindent 12 }}
            {{- else }}
            - configMapRef:
                name: {{ .Values.configMap.name }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.socketVolume.name }}
              mountPath: {{ .Values.socket.path }}
            {{- if .Values.volumeMounts }}
            {{- .Values.volumeMounts | toYaml | nindent 12 }}
            {{- end }}
            {{- if and .Values.serviceAccount.token.name .Values.serviceAccount.token.path }}
            - name: {{ .Values.serviceAccount.token.name }}
              mountPath: {{ .Values.serviceAccount.token.path }}
            {{- end }}
