apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configMap.name }}"
data:
  LOG_LEVEL: "{{ .Values.logging.level }}"
  LOG_FORMAT: "{{ .Values.logging.format }}"
  SOCKET_PATH: "{{ .Values.socket.path }}/{{ .Values.socket.name }}"
  SOCKET_PERMISSIONS: "{{ .Values.socket.permissions }}"
  HTTP_ADDRESS: "{{ .Values.service.host }}:{{ .Values.service.port }}"
  VAULT_ADDRESS: "{{ .Values.vault.address }}"
  VAULT_TRANSIT_KEY: "{{ .Values.vault.transit.key }}"
  VAULT_TRANSIT_PATH: "{{ .Values.vault.transit.path }}"
  {{- if .Values.vault.authentication.path }}
  VAULT_AUTH_PATH: "{{ .Values.vault.authentication.path }}"
  {{- end }}
  {{- if and .Values.serviceAccount.token.path .Values.serviceAccount.token.name }}
  VAULT_JWT_PATH: "{{ .Values.serviceAccount.token.path }}/{{ .Values.serviceAccount.token.name }}"
  {{- end }}
  {{- if .Values.vault.ca.file }}
  VAULT_CA_CERT: {{ .Values.vault.ca.file }}
  {{- end }}
  {{- if .Values.vault.ca.directory }}
  VAULT_CA_PATH: {{ .Values.vault.ca.directory }}
  {{- end }}
