apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configMap.name }}"
data:
  LOG_LEVEL: "{{ .Values.logging.level }}"
  LOG_FORMAT: "{{ .Values.logging.format }}"
  SOCKET_PATH: "{{ .Values.socket.path }}/{{ .Values.socket.name }}"
  SOCKET_PERMISSIONS: "{{ .Values.socket.permissions }}"
  VAULT_ADDRESS: "{{ .Values.vault.address }}"
  VAULT_TRANSIT_KEY: "{{ .Values.vault.transitKey }}"
  HTTP_ADDRESS: "{{ .Values.service.host }}:{{ .Values.service.port }}"
  {{- if and .Values.serviceAccount.token.path .Values.serviceAccount.token.name }}
  VAULT_TOKEN_PATH: "{{ .Values.serviceAccount.token.path }}/{{ .Values.serviceAccount.token.name }}"
  {{- end }}
  {{- if .Values.vault.ca.file }}
  VAULT_CACERT: {{ .Values.vault.ca.file }}
  {{- end }}
  {{- if .Values.vault.ca.directory }}
  VAULT_CAPATH: {{ .Values.vault.ca.directory }}
  {{- end }}
