{{- if .Values.socket.output -}}
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
{{/* TODO: remove this when kms authentication/communication is implemented via service account */}}
      - aesgcm:
          keys:
            - name: key1
              secret: DoOdl1a6BtizC2kYDyGJprSQuKcefB9TTcdePGMmb3k=
{{/* TODO: uncomment this when kms authentication/communication is implemented via service account */}}
{{/*      - kms:*/}}
{{/*          apiVersion: v2*/}}
{{/*          name: vault-kms-provider*/}}
{{/*          endpoint: unix://{{ .Values.socket.path }}/{{ .Values.socket.name }}*/}}
{{/*          timeout: 3s*/}}
      - identity: {}
{{- end }}
