{{- if .Values.encryption.output -}}
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      {{- if .Values.encryption.enabled }}
      - kms:
          apiVersion: v2
          name: vault-kms-provider
          endpoint: unix://{{ .Values.socket.hostPath }}/{{ .Values.socket.name }}
          timeout: 3s
      {{- end }}
      {{- if .Values.encryption.fallback }}
      {{/*  TODO: remove this when a fix is released for k8s kmsv2  */}}
      - aesgcm:
          keys:
            - name: key1
              secret: DoOdl1a6BtizC2kYDyGJprSQuKcefB9TTcdePGMmb3k=
      - identity: {}
      {{- end }}
{{- end }}
