version: "3.9"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.19
    container_name: etcd
    hostname: localhost
    environment:
      ETCD_NAME: etcd0
      ETCD_INITIAL_CLUSTER: etcd0=http://127.0.0.1:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://127.0.0.1:2380
      ETCD_ADVERTISE_CLIENT_URLS: https://127.0.0.1:2379,https://127.0.0.1:4001
      ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:2379,https://0.0.0.0:4001
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster-1
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_KEY_FILE: /etc/ssl/certs/tls.key
      ETCD_CERT_FILE: /etc/ssl/certs/tls.crt
      ETCD_TRUSTED_CA_FILE: /etc/ssl/certs/ca.crt
      ETCD_PEER_AUTO_TLS: true
    volumes:
      - /tmp/certs:/etc/ssl/certs
    network_mode: host
    expose:
      - 4001:4001
      - 2380:2380
      - 2379:2379
