logging:
  level: debug

volumes:
  - name: vault-ca-certificate
    secret:
      secretName: test-certs

volumeMounts:
  - name: vault-ca-certificate
    mountPath: /etc/ssl/certs
    readOnly: true

role:
  name: vault-kms-access
  rules:
    - apiGroups: {}
    - resources: secrets
    - verbs:
        - get
        - create
