replicaCount: 1

image:
  repository: ruddickmg/vault-kms-provider
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.0"

configuration:
  name: vault-kms-provider-configuration

nodeLabel:
  key: &label-key node-role.kubernetes.io/control-plane
  value: &label-value "true"

socket:
  name: vault-kms-provider.sock
  path: sockets
  permissions: any
  output: false

socketVolume:
  mountPath: &mount-path /run
  name: &volume-name vault-kms-provider-socket-volume
  claim: &volume-claim-name socket-volume
  storageClass: unix-socket-storage
  size: 300mi

vault:
  token: "placeholder"
  address: https://vault.vault.cluster.svc.local:8200
  transitKey: vault-kms-provider

nodeSelector:
  *label-key: *label-value

tolerations:
  - key: *label-key
    operator: "Equal"
    value: *label-value
    effect: "NoSchedule"

volumes:
  - name: *volume-name
    persistentVolumeClaim:
      claimName: *volume-claim-name

volumeMounts:
  - mountPath: *mount-path
    name: *volume-name

priorityClassName: system-cluster-critical

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

affinity: {}
