injector:
  enabled: false
global:
  enabled: true
  tlsDisable: false
server:
  extraEnvironmentVars:
#    VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8400
    VAULT_CACERT: /vault/userconfig/test-certs/ca.crt
    VAULT_ADDR: https://127.0.0.1:8200
  extraVolumes:
    - type: secret
      name: test-certs
  dev:
    enabled: true
  standalone:
    enabled: true
    config: |
      cluster_addr  = "https://127.0.0.1:8201"
      api_addr      = "https://127.0.0.1:8200"
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_disable = 0
        tls_cert_file = "/vault/userconfig/test-certs/tls.crt"
        tls_key_file = "/vault/userconfig/test-certs/tls.key"
      }
      storage "file" {
        path = "/vault/data"
      }