injector:
  enabled: false
global:
  enabled: true
  tlsDisable: false
server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/test-certs/ca.crt
  extraVolumes:
    - type: secret
      name: test-certs
  standalone:
    enabled: true
    config: |
      cluster_addr  = "https://127.0.0.1:8201"
      api_addr      = "https://127.0.0.1:8200"
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_disable = 0
        tls_cert_file = "/vault/userconfig/test-certs/tls.crt"
        tls_key_file = "/vault/userconfig/test-certs/tls.key"
      }
      storage "file" {
        path = "/vault/data"
      }